# Generated by Django 2.1.2 on 2019-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='value',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
