# Generated by Django 2.1.2 on 2019-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredients_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooktime',
            field=models.SmallIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.CharField(max_length=20, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image_step'),
        ),
    ]
